### ISSUE TITLE
doesn't work when there is nothing enabled. 

### ISSUE THREAD

**Issue by kundeng** [sspacelynx/toggle-wsl#1]
If nothing is enabled, the script should ideally function by enabling all features, shouldn't it?

**Comment by nickbeth** [comment]
It is by design that if you run the script in a situation where nothing is enabled, the script will not do anything. The script is intended to save the current features status, disable all and re-enable them once you re-run it. If nothing is enabled the first time you run it, there's no way of knowing what the user might want to enable, and we cannot expect every user to inspect the script's source code to find out what the script will enable for them.
Moreover, enabling optional features is best done through this Windows UI: [Add, remove, or hide Windows features](https://learn.microsoft.com/en-us/windows/client-management/client-tools/add-remove-hide-features). A script here would be redundant.
